import { describe, it, expect } from "vitest";
import {
  isAutoGeneratedName,
  labelDeleteOp,
  labelSetOps,
  markFunctionOps,
  regionSetOp,
  unmarkFunctionOps,
} from "./edits.js";
import { loadProjectFile } from "../../node-files.js";

/**
 * What an edit does to identity, now that there is only one rule.
 *
 * There used to be a question here — which existing label's id a write should
 * adopt — and two answers that disagreed: the browser reused whatever resolved
 * at the address, including built-in platform names, so naming `$FFD2` adopted
 * `CHROUT`'s derived id.
 *
 * The question is gone rather than answered. **Naming adds.** An id is minted by
 * the writer, never inferred from an address, so nothing can be adopted by
 * accident and two people naming one address get two claims rather than one
 * silently replacing the other.
 */

const gridrunner = () => loadProjectFile("assets/gridrunner/gridrunner.re64");

/** Inside the PRG, so a layer supplies the bytes, but nothing names it. */
const UNNAMED = 0x8f00;
/** CINV — named by the built-in C64 layer and by nothing in this project. */
const PLATFORM_ONLY = 0x0314;
/** $8000, which this project names `initializeDataJumpAddress`. */
const NAMED = 0x8000;

describe("naming an address", () => {
  it("mints a fresh id, whatever is already there", () => {
    const loaded = gridrunner();
    const [op] = labelSetOps(loaded, UNNAMED, "Found").ops;
    expect(op.op).toBe("claim.add");
    if (op.op !== "claim.add") throw new Error("shape");
    expect(op.claim.id).toMatch(/^clm_/);

    // Stored as an offset into the layer supplying those bytes, which is what
    // makes the claim travel if that layer is ever linked somewhere else. The
    // caller said `$8F00` and never sees this: the loader adds the layer's
    // start back, and every tool answer is absolute.
    const owner = loaded.map.layerAt(UNNAMED)!;
    expect(op.claim.frame).toEqual({ space: "layer", layer: owner.id });
    expect(op.claim.at).toBe(UNNAMED - owner.start);
  });

  it("never adopts a built-in platform name's identity", () => {
    // The bug this rule replaced: a derived id describes where a name came
    // from, and is not something a project may claim.
    const loaded = gridrunner();
    const [op] = labelSetOps(loaded, PLATFORM_ONLY, "MyVector").ops;
    if (op.op !== "claim.add") throw new Error("shape");
    expect(op.claim.id).toMatch(/^clm_/);
  });

  it("adds beside a name somebody chose, and says whose it joined", () => {
    const loaded = gridrunner();
    const built = labelSetOps(loaded, NAMED, "SecondName");

    expect(built.addedBeside).toBe("initializeDataJumpAddress");
    // And pins what was showing, so a second name does not silently rename
    // every reference to the address.
    expect(built.ops.some((o) => o.op === "primary.set")).toBe(true);
  });

  it("names an address no layer supplies, with no symbols layer to invent", () => {
    // On this machine every variable lives in zero page, so this was roughly
    // half of what a person contributes — and it used to require creating a
    // layer to hold the name.
    const loaded = gridrunner();
    const [op] = labelSetOps(loaded, 0x00fe, "scratch").ops;
    expect(op.op).toBe("claim.add");
  });

  it("declines to delete what the project does not name", () => {
    expect(labelDeleteOp(gridrunner(), PLATFORM_ONLY)).toBeUndefined();
  });
});

describe("marking a function", () => {
  it("rewrites an invented name so the prefix matches the type", () => {
    const loaded = gridrunner();
    const [op] = markFunctionOps(loaded, UNNAMED);
    if (op.op !== "claim.add") throw new Error("shape");
    expect(op.claim.name).toBe("sub_8F00");
    expect(op.claim.root).toBe("routine");
  });

  it("keeps a name somebody chose", () => {
    const loaded = gridrunner();
    const [op] = markFunctionOps(loaded, NAMED);
    const name = op.op === "claim.add" ? op.claim.name : (op as { fields: { name?: string } }).fields.name;
    expect(name).toBe("initializeDataJumpAddress");
  });

  it("deletes an invented name when cleared, rather than leaving a duplicate", () => {
    const loaded = gridrunner();
    // Mark it first so there is something to clear.
    const marked = markFunctionOps(loaded, UNNAMED);
    expect(marked).toHaveLength(1);
    expect(isAutoGeneratedName("sub_8F00")).toBe(true);
  });

  it("does nothing where there is no name to clear", () => {
    expect(unmarkFunctionOps(gridrunner(), UNNAMED)).toEqual([]);
  });
});

describe("declaring what a span holds", () => {
  it("adds, rather than guessing which claim it revises", () => {
    // The three-case heuristic is gone. It made a write's identity depend on
    // what the caller had synced, so the same call had two outcomes.
    const loaded = gridrunner();
    const existing = loaded.claims.find((c) => c.name === "characterSetData")!;
    const op = regionSetOp(loaded, existing.at, existing.at + existing.extent!, "data", "same");

    expect(op.op).toBe("claim.add");
    if (op.op !== "claim.add") throw new Error("shape");
    expect(op.claim.id).not.toBe(existing.id);
    // Rooted, or a span nothing names would stop rendering once inclusion is
    // reachability.
    expect(op.claim.root).toBe("data");
  });

  it("revises only when told which, by id", () => {
    const loaded = gridrunner();
    const existing = loaded.claims.find((c) => c.name === "characterSetData")!;
    const op = regionSetOp(
      loaded, existing.at, existing.at + 0x20, "bitmap", "charSet",
      undefined, undefined, undefined, existing.id
    );
    expect(op).toMatchObject({ op: "claim.set", id: existing.id });
  });

  it("refuses a span no layer supplies, since there are no bytes to read", () => {
    expect(() => regionSetOp(gridrunner(), 0x00fe, 0x0100, "data")).toThrow(/nothing there to/);
  });
});
