import { describe, it, expect } from "vitest";
import {
  isAutoGeneratedName,
  labelDeleteOp,
  labelSetOp,
  markFunctionOps,
  projectLabelAt,
  regionSetOp,
  unmarkFunctionOps,
} from "./edits.js";
import { loadProjectFile } from "../../node-files.js";

/**
 * One rule for reusing a label's identity, because there were two.
 *
 * The browser reused whatever label resolved at an address, which includes the
 * built-in platform names — so naming $FFD2 adopted CHROUT's derived id and
 * minted a project label carrying an identity it had no claim to.
 */

const gridrunner = () => loadProjectFile("assets/gridrunner.re64");

/** Inside the PRG, so a layer owns it, but nothing names it. */
const UNNAMED = 0x8f00;
const HEX = "8F00";
/** CINV — named by the built-in C64 layer and by nothing in this project. */
const PLATFORM_ONLY = 0x0314;

describe("which identity an edit claims", () => {
  it("reuses the id of a project label already at the address", () => {
    const loaded = gridrunner();
    const op = labelSetOp(loaded, 0x8100, "Renamed");
    const existing = projectLabelAt(loaded, (op as { layerId: string }).layerId, 0x8100);

    expect(existing).toBeDefined();
    expect(op).toMatchObject({ op: "label.set", id: existing!.id, name: "Renamed" });
  });

  it("mints a new id where the project has no label", () => {
    const loaded = gridrunner();
    const op = labelSetOp(loaded, UNNAMED, "Fresh") as { id: string; layerId: string };
    expect(op.id).toMatch(/^lbl_/);
    expect(projectLabelAt(loaded, op.layerId, UNNAMED)).toBeUndefined();
  });

  it("never adopts a built-in platform label's identity", () => {
    // $0314 is CINV in the built-in C64 layer and nowhere in this project. Its
    // id is derived from where it came from; a project has no claim on it.
    const loaded = gridrunner();
    const builtIn = loaded.map.getLabels().getLabelsAt(PLATFORM_ONLY);
    expect(builtIn.map((l) => l.source.kind)).toEqual(["platform"]);

    const op = labelSetOp(loaded, PLATFORM_ONLY, "MyVector") as { id: string };
    expect(op.id).not.toBe(builtIn[0].id);
    expect(op.id).toMatch(/^lbl_/);
  });

  it("reuses a project label even where a built-in shares the address", () => {
    // $FFD2 carries both ROM_CHROUT, which this project declares, and the
    // built-in CHROUT. The project's own is the one with an identity to keep.
    const loaded = gridrunner();
    const layerId = (labelSetOp(loaded, 0xffd2, "x") as { layerId: string }).layerId;
    const declared = projectLabelAt(loaded, layerId, 0xffd2);

    expect(declared?.name).toBe("ROM_CHROUT");
    expect((labelSetOp(loaded, 0xffd2, "Renamed") as { id: string }).id).toBe(declared!.id);
  });

  it("declines to delete what the project does not own", () => {
    expect(labelDeleteOp(gridrunner(), UNNAMED)).toBeUndefined();
  });
});

describe("marking a function", () => {
  it("rewrites an invented name so the prefix matches the type", () => {
    // Leaving loc_XXXX tagged as a function would contradict itself.
    expect(isAutoGeneratedName("loc_8100")).toBe(true);
    expect(isAutoGeneratedName("DrawGrid")).toBe(false);

    const ops = markFunctionOps(gridrunner(), UNNAMED, `loc_${HEX}`);
    expect(ops[0]).toMatchObject({ name: `sub_${HEX}`, type: "function" });
  });

  it("keeps a name somebody chose", () => {
    const ops = markFunctionOps(gridrunner(), 0x8100, "InitializeGame");
    expect(ops[0]).toMatchObject({ name: "InitializeGame", type: "function" });
  });

  it("names an address that had none, which is how unreferenced code gets decoded", () => {
    const ops = markFunctionOps(gridrunner(), UNNAMED);
    expect(ops[0]).toMatchObject({ name: `sub_${HEX}`, type: "function" });
  });

  it("deletes an invented name when cleared, rather than leaving a duplicate", () => {
    const loaded = gridrunner();
    const set = labelSetOp(loaded, 0x8100, "sub_8100", "function");
    expect(set).toMatchObject({ name: "sub_8100" });

    // Against the real project, $8100 is named InitializeGame by a person.
    const cleared = unmarkFunctionOps(loaded, 0x8100);
    expect(cleared[0]).toMatchObject({ op: "label.set", type: "address" });
  });

  it("does nothing where there is no label to clear", () => {
    expect(unmarkFunctionOps(gridrunner(), UNNAMED)).toEqual([]);
  });
});

describe("regions", () => {
  it("reuses the id of a region with the same start", () => {
    const loaded = gridrunner();
    const declared = loaded.map.getAllRegions()[0];
    const op = regionSetOp(loaded, declared.start, declared.end, "data") as { id: string };
    expect(op.id).toBe(declared.id);
  });

  it("mints one for a span nothing declares", () => {
    const op = regionSetOp(gridrunner(), 0x8f00, 0x8f10, "text", "blurb") as { id: string };
    expect(op.id).toMatch(/^rgn_/);
  });
});
