import { Layer, layerKindAt, layerRegionAt } from "./layer.js";
import { Label, LabelIndex } from "./label.js";
import { Region, RegionKind } from "./region.js";

export interface ReadResult {
  value: number;
  layer: Layer;
}

/**
 * A stack of memory layers. Index 0 is the top (highest priority).
 * When reading, the first layer containing the address wins.
 */
export class MemoryMap {
  private layers: Layer[] = [];

  /**
   * Project-level choice of which label to show at an address.
   *
   * Not per-layer: two layers can hold labels at one address, so the choice is
   * a display preference over the whole map rather than an annotation on any
   * one layer's content.
   */
  primaryLabels = new Map<number, string>();
  /**
   * Which label each referring site means, by the site's own address.
   *
   * Held here rather than in a label index because `getLabels()` builds a new
   * one on every call — the bindings have to outlive that.
   */
  labelUses = new Map<number, string>();

  getLayers(): readonly Layer[] {
    return this.layers;
  }

  getLayerCount(): number {
    return this.layers.length;
  }

  /** Adds a layer. Defaults to top (index 0) if index not specified. */
  addLayer(layer: Layer, index?: number): void {
    if (index === undefined) {
      this.layers.unshift(layer);
    } else {
      if (index < 0 || index > this.layers.length) {
        throw new Error("Index out of bounds");
      }
      this.layers.splice(index, 0, layer);
    }
  }

  removeLayer(index: number): Layer {
    if (index < 0 || index >= this.layers.length) {
      throw new Error("Index out of bounds");
    }
    return this.layers.splice(index, 1)[0];
  }

  moveLayer(fromIndex: number, toIndex: number): void {
    if (fromIndex < 0 || fromIndex >= this.layers.length) {
      throw new Error("fromIndex out of bounds");
    }
    if (toIndex < 0 || toIndex >= this.layers.length) {
      throw new Error("toIndex out of bounds");
    }
    const [layer] = this.layers.splice(fromIndex, 1);
    this.layers.splice(toIndex, 0, layer);
  }

  readByte(address: number): number | undefined {
    for (const layer of this.layers) {
      const value = layer.readByte(address);
      if (value !== undefined) {
        return value;
      }
    }
    return undefined;
  }

  readByteWithSource(address: number): ReadResult | undefined {
    for (const layer of this.layers) {
      const value = layer.readByte(address);
      if (value !== undefined) {
        return { value, layer };
      }
    }
    return undefined;
  }

  readBytes(address: number, length: number): (number | undefined)[] {
    const result: (number | undefined)[] = [];
    for (let i = 0; i < length; i++) {
      result.push(this.readByte(address + i));
    }
    return result;
  }

  /**
   * Get all labels from all layers, plus labels generated by each layer's
   * named regions.
   */
  getLabels(): LabelIndex {
    const index = new LabelIndex();

    for (const layer of this.layers) {
      index.addLabels(layer.getLabels());
      index.addLabels(layer.regions.generateLabels());
    }
    index.setPrimaryLabels(this.primaryLabels);
    // Applied here rather than by the caller: this returns a fresh index every
    // call, so anything set on the result is discarded.
    for (const [site, labelId] of this.labelUses) index.bindUse(site, labelId);

    return index;
  }

  /**
   * The innermost declared region at an address.
   *
   * Resolution follows the same z-order rule as bytes: the topmost layer that
   * supplies a byte is the one whose annotations apply. Reordering the stack
   * therefore moves regions with their content, and there is no cross-layer
   * priority to arbitrate.
   */
  getRegionAt(address: number): Region | undefined {
    const layer = this.readByteWithSource(address)?.layer;
    return layer ? layerRegionAt(layer, address) : undefined;
  }

  /**
   * The effective region kind at an address, falling back to the owning
   * layer's default. Undefined where no layer supplies a byte.
   */
  getKindAt(address: number): RegionKind | undefined {
    const layer = this.readByteWithSource(address)?.layer;
    return layer ? layerKindAt(layer, address) : undefined;
  }

  /** Every jumptable region across all layers, for entry point extraction. */
  getJumptables(): readonly Region[] {
    return this.layers.flatMap((layer) => [...layer.regions.getJumptables()]);
  }

  /** The topmost layer supplying a byte at this address. */
  layerAt(address: number): Layer | undefined {
    return this.readByteWithSource(address)?.layer;
  }

  /** Every declared region across all layers, sorted by start address. */
  getAllRegions(): readonly Region[] {
    return this.layers
      .flatMap((layer) => [...layer.regions.getAllRegions()])
      .sort((a, b) => a.start - b.start);
  }

  /**
   * Give a region to the layer that owns its start address.
   *
   * Returns the owning layer, or undefined when no layer covers the address —
   * a region declared over unmapped memory has nothing to annotate.
   */
  attachRegion(region: Region): Layer | undefined {
    const layer = this.readByteWithSource(region.start)?.layer;
    layer?.regions.addRegion(region);
    return layer;
  }
}
